# -*- coding: utf-8 -*-
"""annglcmhyperparameter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFUwdtBijMprvdFiEXZ1lLNo0ponqIK-
"""

import numpy as np
import os
import cv2
import zipfile
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import time
import math
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import skimage.feature as skf

from google.colab import userdata
os.environ['KAGGLE_USERNAME'] = userdata.get('kaggleName')
os.environ['KAGGLE_KEY'] = userdata.get('kaggleKey')

!kaggle datasets download -d phucthaiv02/butterfly-image-classification
!unzip -q butterfly-image-classification.zip -d dataset

def load_images_from_csv(csv_path, image_folder, target_size=(96, 96), max_samples_per_class=200):
    df = pd.read_csv(csv_path)
    class_names = sorted(df['label'].unique())
    label_dict = {name: idx for idx, name in enumerate(class_names)}

    images, labels = [], []
    counter = {cls: 0 for cls in class_names}

    for _, row in df.iterrows():
        filename = row['filename']
        label = row['label']
        if counter[label] >= max_samples_per_class:
            continue

        img_path = os.path.join(image_folder, filename)
        if not os.path.exists(img_path):
            print(f"File not found: {img_path}")
            continue

        img = cv2.imread(img_path)
        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, target_size)
        img = img.astype(np.float32) / 255.0

        images.append(img)
        labels.append(label_dict[label])
        counter[label] += 1

    return np.array(images), np.array(labels), class_names, label_dict

csv_path = "dataset/Training_set.csv"
image_folder = "dataset/train"
images, labels, class_names, label_dict = load_images_from_csv(csv_path, image_folder)

X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

def calculate_glcm(image, distance=1, angle=0, levels=256):
    offset_x = int(round(distance * math.cos(angle)))
    offset_y = int(round(distance * math.sin(angle)))
    glcm = np.zeros((levels, levels), dtype=np.uint32)

    height, width = image.shape
    for y in range(max(-offset_y, 0), min(height, height - offset_y)):
        for x in range(max(-offset_x, 0), min(width, width - offset_x)):
            i = image[y, x]
            j = image[y + offset_y, x + offset_x]
            glcm[i, j] += 1
            glcm[j, i] += 1

    glcm = glcm.astype(np.float32)
    if np.sum(glcm) > 0:
        glcm /= np.sum(glcm)
    return glcm

def extract_glcm_features(images, distances=[1, 2, 3], angles=[0, np.pi/4, np.pi/2, 3*np.pi/4], levels=16):
    features = []
    for idx, img in enumerate(images):
        if idx % 100 == 0:
            print(f"Processing image {idx+1}/{len(images)}")

        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        gray = (gray * (levels - 1)).astype(np.uint8)
        glcm_features = []

        for d in distances:
            for a in angles:
                glcm = calculate_glcm(gray, d, a, levels)
                i, j = np.indices(glcm.shape)

                # More GLCM statistics
                contrast = np.sum((i - j)**2 * glcm)
                energy = np.sum(glcm**2)
                homogeneity = np.sum(glcm / (1 + (i - j)**2))
                entropy = -np.sum(glcm * np.log2(glcm + 1e-10))

                mean_i = np.sum(i * np.sum(glcm, axis=1))
                mean_j = np.sum(j * np.sum(glcm, axis=0))
                std_i = np.sqrt(np.sum((i - mean_i)**2 * np.sum(glcm, axis=1))) + 1e-8
                std_j = np.sqrt(np.sum((j - mean_j)**2 * np.sum(glcm, axis=0))) + 1e-8
                correlation = np.sum((i - mean_i) * (j - mean_j) * glcm) / (std_i * std_j)

                glcm_features.extend([contrast, energy, homogeneity, correlation, entropy])

        # Add color histograms (3 channels, 8 bins each)
        for channel in range(3):
            hist, _ = np.histogram(img[:,:,channel], bins=8, range=(0, 1))
            glcm_features.extend(hist / np.sum(hist))

        # Add simple edge features
        sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
        sobel_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
        edge_mag = np.sqrt(sobel_x**2 + sobel_y**2)
        edge_features = [np.mean(edge_mag), np.std(edge_mag)]
        glcm_features.extend(edge_features)

        features.append(glcm_features)
    return np.array(features)

# Apply PCA to reduce feature dimensions
def apply_pca(train_features, test_features, n_components=0.95):
    print("Applying PCA...")
    pca = PCA(n_components=n_components)
    train_reduced = pca.fit_transform(train_features)
    test_reduced = pca.transform(test_features)
    print(f"Reduced from {train_features.shape[1]} to {train_reduced.shape[1]} features")
    return train_reduced, test_reduced, pca

# Extract enhanced features
print("Extracting GLCM features for training set...")
glcm_train = extract_glcm_features(X_train)
print("Extracting GLCM features for test set...")
glcm_test = extract_glcm_features(X_test)

# Flatten images and combine with GLCM
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

X_train_combined = np.hstack([X_train_flat, glcm_train])
X_test_combined = np.hstack([X_test_flat, glcm_test])

# Apply PCA
X_train_reduced, X_test_reduced, pca = apply_pca(X_train_combined, X_test_combined, n_components=100)

# Normalize
scaler = StandardScaler()
X_train_combined = scaler.fit_transform(X_train_reduced)
X_test_combined = scaler.transform(X_test_reduced)

class NeuralNetwork:
    def __init__(self, input_size, hidden_layers, output_size, dropout_rates=None, lambd=0.001):
        self.layer_sizes = [input_size] + hidden_layers + [output_size]
        self.num_layers = len(self.layer_sizes) - 1
        self.weights = []
        self.biases = []
        self.dropout_rates = dropout_rates or [0.0] * self.num_layers
        self.lambd = lambd

        # Initialize weights with He initialization
        for i in range(self.num_layers):
            w = np.random.randn(self.layer_sizes[i], self.layer_sizes[i+1]) * np.sqrt(2.0 / self.layer_sizes[i])
            b = np.zeros((1, self.layer_sizes[i+1]))
            self.weights.append(w)
            self.biases.append(b)

    def relu(self, x):
        return np.maximum(0, x)

    def relu_deriv(self, x):
        return (x > 0).astype(np.float32)

    def leaky_relu(self, x, alpha=0.01):
        return np.maximum(alpha * x, x)

    def leaky_relu_deriv(self, x, alpha=0.01):
        dx = np.ones_like(x)
        dx[x < 0] = alpha
        return dx

    def softmax(self, x):
        exps = np.exp(x - np.max(x, axis=1, keepdims=True))
        return exps / np.sum(exps, axis=1, keepdims=True)

    def forward(self, X, training=False):
        self.activations = [X]
        self.zs = []
        self.dropout_masks = []

        # Forward through hidden layers
        for i in range(self.num_layers - 1):
            z = np.dot(self.activations[-1], self.weights[i]) + self.biases[i]
            self.zs.append(z)
            a = self.leaky_relu(z)

            if training and self.dropout_rates[i] > 0:
                mask = np.random.rand(*a.shape) > self.dropout_rates[i]
                a = a * mask / (1 - self.dropout_rates[i])
                self.dropout_masks.append(mask)
            else:
                self.dropout_masks.append(None)

            self.activations.append(a)

        # Output layer with softmax
        z = np.dot(self.activations[-1], self.weights[-1]) + self.biases[-1]
        self.zs.append(z)
        a = self.softmax(z)
        self.activations.append(a)

        return self.activations[-1]

    def backward(self, X, y_true, y_pred, lr):
        m = X.shape[0]
        grads_w = [0] * self.num_layers
        grads_b = [0] * self.num_layers

        # Output layer gradient
        delta = y_pred - y_true
        grads_w[-1] = np.dot(self.activations[-2].T, delta) / m + (self.lambd * self.weights[-1] / m)
        grads_b[-1] = np.sum(delta, axis=0, keepdims=True) / m

        # Hidden layers
        for i in range(self.num_layers - 2, -1, -1):
            delta = np.dot(delta, self.weights[i+1].T)
            if self.dropout_masks[i] is not None:
                delta = delta * self.dropout_masks[i] / (1 - self.dropout_rates[i])
            delta = delta * self.leaky_relu_deriv(self.zs[i])
            grads_w[i] = np.dot(self.activations[i].T, delta) / m + (self.lambd * self.weights[i] / m)
            grads_b[i] = np.sum(delta, axis=0, keepdims=True) / m

        # Apply gradients
        for i in range(self.num_layers):
            self.weights[i] -= lr * grads_w[i]
            self.biases[i] -= lr * grads_b[i]

    def compute_loss(self, y_pred, y_true):
        m = y_true.shape[0]
        log_likelihood = -np.log(np.sum(y_pred * y_true, axis=1) + 1e-10)

        # L2 regularization
        reg_loss = 0
        for i in range(self.num_layers):
            reg_loss += np.sum(self.weights[i]**2)

        return np.sum(log_likelihood)/m + (self.lambd / (2 * m)) * reg_loss

    def predict(self, X):
        y_pred = self.forward(X, training=False)
        return np.argmax(y_pred, axis=1)

def one_hot_encode(y, num_classes):
    encoded = np.zeros((y.size, num_classes))
    encoded[np.arange(y.size), y] = 1
    return encoded

num_classes = len(class_names)
y_train_onehot = one_hot_encode(y_train, num_classes)
y_test_onehot = one_hot_encode(y_test, num_classes)

# Split with one-hot encoded labels
X_train_tune, X_val, y_train_tune_onehot, y_val_onehot = train_test_split(
    X_train_combined, y_train_onehot, test_size=0.2, random_state=42
)

# Also get the non-onehot version for accuracy calculation
_, _, y_train_tune, y_val = train_test_split(
    X_train_combined, y_train, test_size=0.2, random_state=42
)

param_grid = {
    'learning_rate': [0.01, 0.005],
    'hidden_layers': [[256, 128], [128, 64]],
    'dropout_rates': [[0.3, 0.3], [0.5, 0.3]],
    'lambd': [0.001, 0.0005]
}

def hyperparameter_tuning(X_train, y_train_onehot, y_train, X_val, y_val_onehot, y_val, param_grid, epochs=10, batch_size=32):
    best_params = None
    best_acc = 0

    print("Starting hyperparameter tuning...")

    for lr in param_grid['learning_rate']:
        for hidden_layers in param_grid['hidden_layers']:
            for dropout_rates in param_grid['dropout_rates']:
                for l2 in param_grid['lambd']:
                    print(f"Testing: lr={lr}, hidden={hidden_layers}, dropout={dropout_rates}, lambda={l2}")

                    model = NeuralNetwork(
                        input_size=X_train.shape[1],
                        hidden_layers=hidden_layers,
                        output_size=num_classes,
                        dropout_rates=dropout_rates,
                        lambd=l2
                    )

                    for epoch in range(epochs):
                        indices = np.random.permutation(len(X_train))
                        for i in range(0, len(X_train), batch_size):
                            batch = indices[i:i+batch_size]
                            Xb, yb_onehot = X_train[batch], y_train_onehot[batch]
                            y_pred = model.forward(Xb, training=True)
                            model.backward(Xb, yb_onehot, y_pred, lr)

                    val_acc = np.mean(model.predict(X_val) == y_val)
                    print(f"Validation accuracy: {val_acc:.4f}")

                    if val_acc > best_acc:
                        best_acc = val_acc
                        best_params = {
                            'learning_rate': lr,
                            'hidden_layers': hidden_layers,
                            'dropout_rates': dropout_rates,
                            'lambd': l2
                        }

    print(f"Best parameters: {best_params}, best accuracy: {best_acc:.4f}")
    return best_params

# Train with best parameters
best_params = hyperparameter_tuning(X_train_tune, y_train_tune_onehot, y_train_tune,
                                  X_val, y_val_onehot, y_val, param_grid)

# Training with learning rate warmup and cosine annealing
final_model = NeuralNetwork(
    input_size=X_train_combined.shape[1],
    hidden_layers=best_params['hidden_layers'],
    output_size=num_classes,
    dropout_rates=best_params['dropout_rates'],
    lambd=best_params['lambd']
)

def lr_schedule(epoch, initial_lr, warmup=5, max_epochs=100):
    if epoch < warmup:
        return initial_lr * ((epoch + 1) / warmup)
    else:
        # Cosine annealing
        return initial_lr * 0.5 * (1 + np.cos(np.pi * (epoch - warmup) / (max_epochs - warmup)))

# Train with cross-validation for 100 epochs
print("Training final model...")
train_losses = []
val_accuracies = []
max_epochs = 200
patience = 15
best_val_acc = 0
no_improve_count = 0

for epoch in range(max_epochs):
    lr = lr_schedule(epoch, best_params['learning_rate'])
    epoch_losses = []

    # Shuffle training data
    indices = np.random.permutation(len(X_train_combined))

    # Mini-batch training
    for i in range(0, len(X_train_combined), 32):
        batch = indices[i:i+32]
        Xb, yb = X_train_combined[batch], y_train_onehot[batch]
        y_pred = final_model.forward(Xb, training=True)
        loss = final_model.compute_loss(y_pred, yb)
        epoch_losses.append(loss)
        final_model.backward(Xb, yb, y_pred, lr)

    avg_train_loss = np.mean(epoch_losses)
    train_losses.append(avg_train_loss)

    val_preds = final_model.predict(X_test_combined)
    val_acc = np.mean(val_preds == y_test)
    val_accuracies.append(val_acc)

    if (epoch + 1) % 5 == 0 or epoch == 0:
        print(f"Epoch {epoch+1}: Train Loss = {avg_train_loss:.4f}, Val Acc = {val_acc:.4f}, LR = {lr:.6f}")

    # Keep track of best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        no_improve_count = 0
        # Save best weights (not implemented for brevity)
    else:
        no_improve_count += 1

    # Early stopping
    if no_improve_count >= patience:
        print(f"Early stopping at epoch {epoch+1}. Best validation accuracy: {best_val_acc:.4f}")
        break

# Plot learning curves
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(train_losses)
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.subplot(1, 2, 2)
plt.plot(val_accuracies)
plt.title('Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.tight_layout()
plt.show()

def show_predictions(model, X, y, class_names, n=5, cols=5):
    # Select random indices
    indices = np.random.choice(len(X), n)
    samples = X[indices]

    # Extract GLCM features for the selected samples
    glcm = extract_glcm_features(samples, distances=[1, 2, 3], angles=[0, np.pi/4, np.pi/2, 3*np.pi/4], levels=16)
    flat = samples.reshape(n, -1)
    combined = np.hstack([flat, glcm])

    # Apply the same PCA transformation
    combined_pca = pca.transform(combined)

    # Apply the same normalization
    combined_normalized = scaler.transform(combined_pca)

    preds = model.predict(combined_normalized)

    # Calculate number of rows needed
    rows = (n + cols - 1) // cols  # Ceiling division

    # Create figure with appropriate height
    plt.figure(figsize=(3*cols, 3*rows))

    for i in range(n):
        plt.subplot(rows, cols, i+1)
        plt.imshow(samples[i])
        plt.title(f"True: {class_names[y[indices[i]]]} \nPred: {class_names[preds[i]]}")
        plt.axis('off')

    plt.tight_layout()
    plt.show()

# Generate confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

y_pred = final_model.predict(X_test_combined)
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(15, 12))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

print(classification_report(y_test, y_pred, target_names=class_names))

# Show example predictions
show_predictions(final_model, X_test, y_test, class_names, n=15, cols=5)